"""
pages.py — Page Object Model for Oral Ulcer AI Web Application
All selectors use ARIA labels generated by Flutter Web's semantic tree.
"""
import time
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import TimeoutException, NoSuchElementException
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.action_chains import ActionChains


# ─────────────────────────────────────────────────────────────────
#  BASE PAGE — shared helpers
# ─────────────────────────────────────────────────────────────────
class BasePage:
    def __init__(self, driver):
        self.driver = driver

    def _process_xpath(self, xpath):
        import re
        if not xpath:
            return xpath
        # Convert contains(@aria-label, "foo") to (contains(@aria-label, "foo") or contains(., "foo"))
        pattern = r'contains\(@aria-label,\s*([\'"])([^\'"]+)\1\)'
        def replace(match):
            quote = match.group(1)
            text = match.group(2)
            return f'(contains(@aria-label, {quote}{text}{quote}) or contains(., {quote}{text}{quote}))'
        new_xpath = re.sub(pattern, replace, xpath)
        
        # Convert @aria-label="foo" to (@aria-label="foo" or .="foo")
        pattern_eq = r'@aria-label\s*=\s*([\'"])([^\'"]+)\1'
        def replace_eq(match):
            quote = match.group(1)
            text = match.group(2)
            return f'(@aria-label={quote}{text}{quote} or .={quote}{text}{quote})'
        new_xpath = re.sub(pattern_eq, replace_eq, new_xpath)

        # Convert contains(@role, "textbox") to (contains(@role, "textbox") or self::input)
        new_xpath = new_xpath.replace('contains(@role,"textbox")', '(contains(@role,"textbox") or self::input)')
        new_xpath = new_xpath.replace("contains(@role,'textbox')", "(contains(@role,'textbox') or self::input)")
        return new_xpath

    def wait_for_element(self, xpath, timeout=8):
        """Waits for element to be visible and returns it, else None."""
        xpath = self._process_xpath(xpath)
        try:
            return WebDriverWait(self.driver, timeout).until(
                EC.visibility_of_element_located((By.XPATH, xpath))
            )
        except TimeoutException:
            return None

    def wait_for_clickable(self, xpath, timeout=8):
        """Waits for element to be clickable and returns it, else None."""
        xpath = self._process_xpath(xpath)
        try:
            return WebDriverWait(self.driver, timeout).until(
                EC.element_to_be_clickable((By.XPATH, xpath))
            )
        except TimeoutException:
            return None

    def find_element(self, xpath):
        """Finds element without wait; returns None on failure."""
        xpath = self._process_xpath(xpath)
        try:
            return self.driver.find_element(By.XPATH, xpath)
        except Exception:
            return None

    def find_elements(self, xpath):
        """Finds all matching elements; returns empty list on failure."""
        xpath = self._process_xpath(xpath)
        try:
            return self.driver.find_elements(By.XPATH, xpath)
        except Exception:
            return []

    def wait_for_element_with_scroll(self, xpath, timeout=8):
        """Finds an element, scrolling down if not immediately present in DOM.
        Hard cap: will never block longer than 30s total to prevent session timeouts.
        """
        processed_xpath = self._process_xpath(xpath)
        print(f"[DEBUG] Searching for locator: {processed_xpath} (timeout={timeout}s) | Current URL: {self.driver.current_url}")
        start_time = time.time()
        MAX_TOTAL_WAIT = 30  # hard cap in seconds

        try:
            el = WebDriverWait(self.driver, 2).until(
                EC.presence_of_element_located((By.XPATH, processed_xpath))
            )
            self.driver.execute_script("arguments[0].scrollIntoView({block: 'center'});", el)
            time.sleep(0.3)
            print(f"[DEBUG] Found locator immediately: {processed_xpath}")
            return el
        except Exception as e:
            print(f"[DEBUG] Immediate search exception type: {type(e).__name__} for {processed_xpath}")
            pass

        for i in range(10):
            if time.time() - start_time > MAX_TOTAL_WAIT:
                print(f"[DEBUG] Total timeout exceeded ({MAX_TOTAL_WAIT}s) at scroll {i+1}, giving up")
                break
            try:
                el = WebDriverWait(self.driver, 1.0).until(
                    EC.presence_of_element_located((By.XPATH, processed_xpath))
                )
                self.driver.execute_script("arguments[0].scrollIntoView({block: 'center'});", el)
                time.sleep(0.3)
                print(f"[DEBUG] Found locator after scroll {i+1}: {processed_xpath}")
                return el
            except Exception as e:
                print(f"[DEBUG] Scroll {i+1} exception type: {type(e).__name__} for {processed_xpath}")
                try:
                    self.driver.execute_script("document.body.focus();")
                    self.driver.find_element(By.TAG_NAME, 'body').send_keys(Keys.PAGE_DOWN)
                except Exception:
                    pass
                try:
                    self.driver.execute_script("""
                        const el = document.querySelector('flutter-view') || document.body;
                        el.dispatchEvent(new WheelEvent('wheel', { deltaY: 500, bubbles: true }));
                    """)
                except Exception:
                    self.driver.execute_script("window.scrollBy(0, 500);")
                time.sleep(0.5)

        try:
            el = WebDriverWait(self.driver, 2).until(
                EC.presence_of_element_located((By.XPATH, processed_xpath))
            )
            print(f"[DEBUG] Found locator in final attempt: {processed_xpath}")
            return el
        except Exception as e:
            print(f"[DEBUG] Final search exception type: {type(e).__name__} for {processed_xpath} | NOT FOUND")
            return None

    def click_element(self, xpath, timeout=8):
        """Clicks element after waiting. Returns True on success."""
        from selenium.common.exceptions import StaleElementReferenceException
        import time

        processed_xpath = self._process_xpath(xpath)
        for attempt in range(2):
            if attempt == 0:
                element = self.wait_for_element_with_scroll(xpath, timeout)
            else:
                element = self.wait_for_element_with_scroll(xpath, timeout=3)
            if not element:
                if attempt == 0:
                    time.sleep(0.5)
                    continue
                print(f"[DEBUG] Click failed: locator {processed_xpath} NOT FOUND")
                return False

            try:
                # Primary: Standard click
                element.click()
                print(f"[DEBUG] Clicked locator via standard click: {processed_xpath}")
                return True
            except StaleElementReferenceException:
                print(f"[DEBUG] StaleElementReferenceException on standard click, retrying... (attempt {attempt+1})")
                time.sleep(0.5)
                continue
            except Exception as e1:
                print(f"[DEBUG] Standard click failed with exception: {type(e1).__name__} for {processed_xpath}")
                # Fallback 1: ActionChains click
                try:
                    from selenium.webdriver.common.action_chains import ActionChains
                    ActionChains(self.driver).move_to_element(element).click().perform()
                    print(f"[DEBUG] Clicked locator via ActionChains: {processed_xpath}")
                    return True
                except StaleElementReferenceException:
                    print(f"[DEBUG] StaleElementReferenceException on ActionChains click, retrying... (attempt {attempt+1})")
                    time.sleep(0.5)
                    continue
                except Exception as e2:
                    print(f"[DEBUG] ActionChains click failed with exception: {type(e2).__name__} for {processed_xpath}")
                    # Fallback 2: JS click (final fallback)
                    try:
                        self.driver.execute_script("arguments[0].click();", element)
                        print(f"[DEBUG] Clicked locator via JS click: {processed_xpath}")
                        return True
                    except StaleElementReferenceException:
                        print(f"[DEBUG] StaleElementReferenceException on JS click, retrying... (attempt {attempt+1})")
                        time.sleep(0.5)
                        continue
                    except Exception as e3:
                        print(f"[DEBUG] JS click failed with exception: {type(e3).__name__} for {processed_xpath}")
                        return False
        return False


    def input_text(self, xpath, text, timeout=8):
        """Clears field and types text. Returns True on success."""
        element = self.wait_for_element_with_scroll(xpath, timeout)
        processed_xpath = self._process_xpath(xpath)
        if element:
            try:
                element.clear()
                element.send_keys(text)
                print(f"[DEBUG] Inputted text '{text}' into locator: {processed_xpath}")
                return True
            except Exception as e:
                print(f"[DEBUG] Input text failed with exception: {type(e).__name__} for {processed_xpath}")
                return False
        else:
            print(f"[DEBUG] Input text failed: locator {processed_xpath} NOT FOUND")
        return False

    def element_exists(self, xpath, timeout=3):
        """Returns True if element is present in DOM within timeout."""
        processed_xpath = self._process_xpath(xpath)
        print(f"[DEBUG] Checking existence of locator: {processed_xpath} (timeout={timeout}s) | Current URL: {self.driver.current_url}")
        try:
            WebDriverWait(self.driver, timeout).until(
                EC.presence_of_element_located((By.XPATH, processed_xpath))
            )
            print(f"[DEBUG] Locator exists: {processed_xpath}")
            return True
        except TimeoutException as e:
            print(f"[DEBUG] Locator does NOT exist: {processed_xpath} (TimeoutException)")
            return False

    def get_element_text(self, xpath, timeout=5):
        """Returns the text content of an element, or empty string."""
        element = self.wait_for_element(xpath, timeout)
        if element:
            return element.text
        return ""

    def inject_print_mock(self):
        """Suppresses browser print dialog so PDF tests don't block execution."""
        script = """
            window.print = function() {
                console.log('Mocked window.print() called — test suite bypass.');
            };
            const _orig = document.createElement.bind(document);
            document.createElement = function(tag) {
                const el = _orig(tag);
                if (tag && tag.toLowerCase() === 'iframe') {
                    Object.defineProperty(el, 'contentWindow', {
                        get: function() {
                            const desc = Object.getOwnPropertyDescriptor(HTMLIFrameElement.prototype, 'contentWindow');
                            const win = desc.get.call(this);
                            if (win && !win.__printMocked__) {
                                win.__printMocked__ = true;
                                win.print = function() {
                                    console.log('Mocked iframe.contentWindow.print() called.');
                                };
                            }
                            return win;
                        }, configurable: true
                    });
                }
                return el;
            };
        """
        try:
            self.driver.execute_script(script)
            return True
        except Exception:
            return False

    def page_loaded(self, keyword, timeout=10):
        """Checks if a keyword appears anywhere in the page DOM (including Shadow DOM)."""
        print(f"[DEBUG] Checking page load with keyword: '{keyword}' (timeout={timeout}s) | Current URL: {self.driver.current_url}")
        script = """
            function findText(root, text) {
                if (!root) return false;
                const content = (root.innerText || root.textContent || '').toLowerCase();
                if (content.includes(text.toLowerCase())) return true;
                
                const children = root.children || [];
                for (let i = 0; i < children.length; i++) {
                    if (findText(children[i], text)) return true;
                }
                if (root.shadowRoot) {
                    if (findText(root.shadowRoot, text)) return true;
                }
                return false;
            }
            return findText(document.body, arguments[0]) || document.title.toLowerCase().includes(arguments[0].toLowerCase());
        """
        start_time = time.time()
        while time.time() - start_time < timeout:
            try:
                if self.driver.execute_script(script, keyword):
                    print(f"[DEBUG] Page loaded successfully with keyword '{keyword}' | result = True")
                    return True
            except Exception as e:
                print(f"[DEBUG] page_loaded JS search exception: {type(e).__name__}")
                pass
            time.sleep(0.5)
        print(f"[DEBUG] Page load FAILED with keyword '{keyword}' | result = False")
        return False



# ─────────────────────────────────────────────────────────────────
#  SPLASH / ONBOARDING PAGES
# ─────────────────────────────────────────────────────────────────
class SplashPage(BasePage):
    SPLASH_INDICATOR = '//*[contains(@aria-label, "Oral Ulcer") or contains(@aria-label, "Saveetha")]'

    def is_splash_visible(self):
        try:
            return "saveetha" in self.driver.title.lower() or self.element_exists(self.SPLASH_INDICATOR, timeout=12)
        except Exception:
            return self.element_exists(self.SPLASH_INDICATOR, timeout=12)


class OnboardingPage(BasePage):
    SKIP_BUTTON       = '//flt-semantics[contains(@role,"button") and contains(@aria-label,"Skip")]'
    GET_STARTED_BTN   = '//flt-semantics[contains(@role,"button") and contains(@aria-label,"Get Started")]'
    CONTINUE_BTN      = '//flt-semantics[contains(@role,"button") and contains(@aria-label,"Continue")]'
    SWIPE_SLIDER      = '//flt-semantics[contains(@aria-label,"Swipe") or contains(@aria-label,"SWIPE")]'

    def click_skip(self):
        return self.click_element(self.SKIP_BUTTON)

    def click_get_started(self):
        return self.click_element(self.GET_STARTED_BTN)

    def click_continue(self):
        return self.click_element(self.CONTINUE_BTN)

    def slide3_visible(self):
        return self.element_exists(self.SWIPE_SLIDER)


# ─────────────────────────────────────────────────────────────────
#  AUTHENTICATION PAGES
# ─────────────────────────────────────────────────────────────────
class LoginPage(BasePage):
    # Toggle / mode switch
    SIGNUP_TOGGLE   = '//*[contains(@role,"button") and (contains(@aria-label,"Sign up") or contains(@aria-label,"Register"))]'

    # Sign-In fields
    EMAIL_INPUT     = '//input[contains(@aria-label, "clinician") or contains(@aria-label, "saveetha") or contains(@aria-label, "Email")] | //input[@type="email"] | (//input)[1]'
    PASSWORD_INPUT  = '(//input[@type="password"])[1]'
    SIGNIN_BTN      = '//*[contains(@role,"button") and contains(., "Sign In")]'

    # Sign-Up extra fields
    NAME_INPUT      = '//input[contains(@aria-label, "Smith") or contains(@aria-label, "Dr.") or contains(@aria-label, "Name")]'
    CONFIRM_PW_INPUT= '(//input[@type="password"])[2]'
    CREATE_BTN      = '//*[contains(@role,"button") and contains(., "Create Account")]'

    # Navigation
    FORGOT_LINK     = '//*[contains(@aria-label,"Forgot") or contains(@aria-label,"forgot")]'
    EYE_TOGGLE      = '//*[contains(@role,"button") and not(normalize-space(.)) and not(@aria-label)]'

    def login(self, email, password):
        self.input_text(self.EMAIL_INPUT, email)
        self.input_text(self.PASSWORD_INPUT, password)
        return self.click_element(self.SIGNIN_BTN)

    def switch_to_signup_mode(self):
        return self.click_element(self.SIGNUP_TOGGLE)

    def register(self, name, email, password, confirm=""):
        self.input_text(self.NAME_INPUT, name)
        self.input_text(self.EMAIL_INPUT, email)
        self.input_text(self.PASSWORD_INPUT, password)
        if confirm:
            self.input_text(self.CONFIRM_PW_INPUT, confirm)
        return self.click_element(self.CREATE_BTN)

    def click_forgot_password(self):
        return self.click_element(self.FORGOT_LINK)

    def toggle_password_visibility(self):
        return self.click_element(self.EYE_TOGGLE)

    def snackbar_exists(self, timeout=5):
        return self.element_exists('//*[contains(@role,"alert")] | //*[contains(@aria-label,"error") or contains(@aria-label,"incorrect")]', timeout)


class ForgotPasswordPage(BasePage):
    EMAIL_INPUT     = '//*[contains(@role,"textbox") and contains(@aria-label,"Email")] | //input'
    SEND_BTN        = '//*[contains(@role,"button") and (contains(@aria-label,"Send") or contains(@aria-label,"Verification"))]'
    SUGGEST_PW_BTN  = '//*[contains(@role,"button") and (contains(@aria-label,"Suggest") or contains(@aria-label,"vpn_key"))]'
    UPDATE_PW_BTN   = '//*[contains(@role,"button") and contains(@aria-label,"Update Password")]'
    CHANGE_EMAIL_BTN= '//*[contains(@role,"button") and contains(@aria-label,"Change Email")]'
    OTP_BOX_1       = '(//*[contains(@role,"textbox")])[1]'
    BACK_BTN        = '//*[contains(@role,"button") and contains(@aria-label,"back")]'

    def request_otp(self, email):
        self.input_text(self.EMAIL_INPUT, email)
        return self.click_element(self.SEND_BTN)

    def click_suggest_password(self):
        return self.click_element(self.SUGGEST_PW_BTN)

    def click_change_email(self):
        return self.click_element(self.CHANGE_EMAIL_BTN)

    def otp_form_visible(self):
        return self.element_exists(self.SUGGEST_PW_BTN, timeout=8)


class ChangePasswordPage(BasePage):
    CURRENT_PW   = '(//*[contains(@role,"textbox") and (contains(@aria-label,"Current") or contains(@aria-label,"current"))])[1] | (//input[@type="password"])[1]'
    NEW_PW       = '(//*[contains(@role,"textbox") and (contains(@aria-label,"New") or contains(@aria-label,"new"))])[1] | (//input[@type="password"])[2]'
    CONFIRM_PW   = '(//*[contains(@role,"textbox") and contains(@aria-label,"Confirm")])[1] | (//input[@type="password"])[3]'
    SUGGEST_BTN  = '//*[contains(@role,"button") and contains(@aria-label,"Suggest")]'
    UPDATE_BTN   = '//*[contains(@role,"button") and contains(@aria-label,"Update Password")]'

    def fill_and_submit(self, current, new_pw, confirm):
        self.input_text(self.CURRENT_PW, current)
        self.input_text(self.NEW_PW, new_pw)
        self.input_text(self.CONFIRM_PW, confirm)
        return self.click_element(self.UPDATE_BTN)

    def click_suggest(self):
        return self.click_element(self.SUGGEST_BTN)


# ─────────────────────────────────────────────────────────────────
#  NAVIGATION
# ─────────────────────────────────────────────────────────────────
class NavigationPage(BasePage):
    TAB_DASHBOARD  = '//*[contains(@role,"button") and contains(., "Dashboard")]'
    TAB_ANALYTICS  = '//*[contains(@role,"button") and contains(., "Analytics")]'
    TAB_HISTORY    = '//*[contains(@role,"button") and contains(., "History")]'
    TAB_SETTINGS   = '//*[contains(@role,"button") and contains(., "Settings")]'
    TAB_PROFILE    = '//*[contains(@role,"button") and contains(., "Profile")]'
    FAB_NEW_CASE   = '//*[contains(@role,"button") and (contains(@aria-label,"add") or contains(@aria-label,"Add") or contains(@aria-label,"New Case") or contains(., "+") or (not(normalize-space(.)) and not(@aria-label) and (contains(@style, "width: 56px") or contains(@style, "height: 56px"))))]'
    EXIT_DIALOG    = '//*[contains(@aria-label,"Exit") or contains(@aria-label,"close application")]'
    TOUR_NEXT      = '//*[contains(@role,"button") and contains(@aria-label,"NEXT")]'
    TOUR_FINISH    = '//*[contains(@role,"button") and contains(@aria-label,"FINISH")]'

    def go_analytics(self):
        return self.click_element(self.TAB_ANALYTICS)

    def go_history(self):
        return self.click_element(self.TAB_HISTORY)

    def go_settings(self):
        return self.click_element(self.TAB_SETTINGS)

    def go_profile(self):
        return self.click_element(self.TAB_PROFILE)

    def click_fab(self):
        return self.click_element(self.FAB_NEW_CASE)


# ─────────────────────────────────────────────────────────────────
#  DASHBOARD PAGE
# ─────────────────────────────────────────────────────────────────
class DashboardPage(BasePage):
    NOTIF_BELL      = '//flt-semantics[contains(@aria-label,"Notifications") and contains(@role,"button")]'
    AVATAR          = '//flt-semantics[contains(@aria-label,"Doctor Profile") and contains(@role,"button")]'
    NEW_CASE_CTA    = '//flt-semantics[contains(@role,"button") and contains(., "New Case")]'
    CASE_CARD       = '(//flt-semantics[contains(@role,"button") and (contains(@aria-label,"Dr. ") or contains(., "Dr. ") or contains(@aria-label,"202") or contains(., "202"))])[1]'
    NOTIF_SHEET     = '//flt-semantics[contains(@aria-label,"CLINICAL ALERTS") or contains(@aria-label,"Clinical Alerts")]'
    CLOSE_SHEET     = '//flt-semantics[contains(@role,"button") and (contains(@aria-label,"Close") or contains(@aria-label,"close"))]'
    STATS_PATIENTS  = '//flt-semantics[contains(@aria-label,"PATIENTS") or contains(@aria-label,"patients")]'

    def open_notifications(self):
        return self.click_element(self.NOTIF_BELL)

    def click_avatar(self):
        return self.click_element(self.AVATAR)

    def click_new_case_cta(self):
        return self.click_element(self.NEW_CASE_CTA)

    def notification_sheet_visible(self):
        return self.element_exists(self.NOTIF_SHEET, timeout=5)

    def dashboard_loaded(self):
        return self.page_loaded("assessment", timeout=12)


# ─────────────────────────────────────────────────────────────────
#  NEW CASE PAGE
# ─────────────────────────────────────────────────────────────────
class NewCasePage(BasePage):
    PATIENT_ID_INPUT = '(//input)[1]'
    SEARCH_BTN       = '//*[contains(@role,"button") and contains(., "Search")]'
    PATIENT_NAME     = '(//input)[2]'
    AGE_INPUT        = '(//input)[3]'
    SEX_DROPDOWN     = '//*[contains(@role,"button") and (contains(@aria-label,"Sex") or contains(@aria-label,"Male") or contains(@aria-label,"Female") or contains(., "Male") or contains(., "Female") or contains(., "Other"))]'

    # Section A
    SMOKING_NO       = '//flt-semantics[contains(@role,"button") and (contains(@aria-label,"No") and (contains(@aria-label,"smoking") or contains(@aria-label,"Smoking")))]'
    SMOKING_CURRENT  = '//flt-semantics[contains(@role,"button") and contains(@aria-label,"Current")]'
    TOBACCO_SWITCH   = '//flt-semantics[contains(@role,"switch") and (contains(@aria-label,"Smokeless Tobacco") or contains(.,"Smokeless Tobacco"))]'
    DIABETES_SWITCH  = '//flt-semantics[contains(@role,"switch") and (contains(@aria-label,"Diabetes") or contains(.,"Diabetes"))]'

    # Section C
    SITE_DROPDOWN    = '//flt-semantics[contains(@role,"button") and (contains(@aria-label,"anatomical") or contains(@aria-label,"site") or contains(@aria-label,"Site") or contains(., "anatomical") or contains(., "site") or contains(., "Site") or contains(., "Tongue") or contains(., "Floor") or contains(., "Buccal"))]'
    SIZE_PLUS        = '//flt-semantics[contains(@aria-label,"Increment Lesion Size") or contains(@aria-label,"increment") or contains(@aria-label,"Increment")]'
    SIZE_MINUS       = '//flt-semantics[contains(@aria-label,"Decrement Lesion Size") or contains(@aria-label,"decrement") or contains(@aria-label,"Decrement")]'
    INDURATION_SW    = '//flt-semantics[contains(@role,"switch") and (contains(@aria-label,"Induration") or contains(.,"Induration"))]'

    # Section D
    LYMPH_NODE_SW    = '//flt-semantics[contains(@role,"switch") and (contains(@aria-label,"Palpable Lymph Node") or contains(.,"Palpable Lymph Node"))]'

    # Submit
    PROCEED_BTN      = '//*[contains(@role,"button") and (contains(@aria-label,"Proceed") or contains(@aria-label,"Image Analysis") or contains(@aria-label,"proceed"))]'

    # Consent dialog
    CONSENT_CB_1     = '(//*[contains(@role,"checkbox")])[1]'
    CONSENT_CB_2     = '(//*[contains(@role,"checkbox")])[2]'
    CONSENT_ACCEPT   = '//*[contains(@role,"button") and (contains(@aria-label,"Accept") or contains(@aria-label,"Continue"))]'
    CONSENT_CANCEL   = '//*[contains(@role,"button") and contains(@aria-label,"Cancel")]'

    def search_patient(self, patient_id):
        self.input_text(self.PATIENT_ID_INPUT, patient_id)
        return self.click_element(self.SEARCH_BTN)

    def fill_basic_info(self, patient_id, name, age):
        self.input_text(self.PATIENT_ID_INPUT, patient_id)
        self.input_text(self.PATIENT_NAME, name)
        self.input_text(self.AGE_INPUT, age)

    def click_proceed(self):
        return self.click_element(self.PROCEED_BTN)

    def accept_consent(self):
        self.click_element(self.CONSENT_CB_1)
        self.click_element(self.CONSENT_CB_2)
        return self.click_element(self.CONSENT_ACCEPT)

    def increment_lesion_size(self, times=3):
        for _ in range(times):
            self.click_element(self.SIZE_PLUS)
        return True
    def expand_section(self, section_name):
        # section_name can be "Demographics", "History", "Examination", "Findings"
        header_xpath = f'//*[contains(@role,"button") and contains(., "{section_name}")]'
        return self.click_element(header_xpath)


# ─────────────────────────────────────────────────────────────────
#  IMAGE UPLOAD PAGE
# ─────────────────────────────────────────────────────────────────
class ImageUploadPage(BasePage):
    CAMERA_BTN     = '//*[contains(@role,"button") and (contains(@aria-label,"Camera") or contains(@aria-label,"camera") or contains(@aria-label,"Retake"))]'
    GALLERY_BTN    = '//*[contains(@role,"button") and (contains(@aria-label,"Gallery") or contains(@aria-label,"gallery"))]'
    PROCESS_BTN    = '//*[contains(@role,"button") and (contains(@aria-label,"Process") or contains(@aria-label,"AI Analysis") or contains(@aria-label,"Analyse"))]'
    DISABLED_BTN   = '//*[contains(@aria-label,"Select an image") or contains(@aria-label,"select an image")]'
    PROGRESS_TEXT  = '//*[contains(@aria-label,"Saving") or contains(@aria-label,"Running") or contains(@aria-label,"Loading")]'

    def gallery_button_exists(self):
        return self.element_exists(self.GALLERY_BTN)

    def camera_button_exists(self):
        return self.element_exists(self.CAMERA_BTN)

    def process_button_disabled(self):
        return self.element_exists(self.DISABLED_BTN)

    def process_button_active(self):
        return self.element_exists(self.PROCESS_BTN)


# ─────────────────────────────────────────────────────────────────
#  AI RESULT SCREEN
# ─────────────────────────────────────────────────────────────────
class AiResultPage(BasePage):
    RISK_BANNER    = '//*[contains(@aria-label,"HIGH RISK") or contains(@aria-label,"INTERMEDIATE") or contains(@aria-label,"LOW RISK") or contains(@aria-label,"Risk")]'
    RETURN_BTN     = '//*[contains(@role,"button") and (contains(@aria-label,"Return") or contains(@aria-label,"Dashboard"))]'
    RISK_FACTORS   = '//*[contains(@aria-label,"Risk Factor") or contains(@aria-label,"Contributing")]'
    CONFIDENCE     = '//*[contains(@aria-label,"Confidence") or contains(@aria-label,"confidence")]'

    def result_loaded(self):
        return self.page_loaded("risk", timeout=15)

    def return_to_dashboard(self):
        return self.click_element(self.RETURN_BTN)


# ─────────────────────────────────────────────────────────────────
#  HISTORY SCREEN
# ─────────────────────────────────────────────────────────────────
class HistoryPage(BasePage):
    SEARCH_INPUT    = '//*[contains(@role,"textbox") and (contains(@aria-label,"Search") or contains(@aria-label,"search"))]'
    SEARCH_CLEAR    = '//flt-semantics[@role="button" and not(normalize-space(.)) and not(@aria-label)]'

    FILTER_ALL      = '//*[contains(@role,"button") and contains(@aria-label,"ALL")]'
    FILTER_HIGH     = '//*[contains(@role,"button") and contains(@aria-label,"HIGH")]'
    FILTER_INTER    = '//*[contains(@role,"button") and contains(@aria-label,"INTERMEDIATE")]'
    FILTER_LOW      = '//*[contains(@role,"button") and contains(@aria-label,"LOW")]'

    BIOPSY_FILTER   = '//*[contains(@role,"button") and contains(@aria-label,"Biopsy")]'
    BLEEDING_FILTER = '//*[contains(@role,"button") and (contains(@aria-label,"Bleeding") or contains(@aria-label,"bleeding"))]'
    INDUR_FILTER    = '//*[contains(@role,"button") and (contains(@aria-label,"Induration") or contains(@aria-label,"induration"))]'

    GRID_TOGGLE     = '//*[contains(@role,"button") and (contains(@aria-label,"Gallery") or contains(@aria-label,"List") or contains(@aria-label,"Grid") or contains(@aria-label,"grid"))]'
    DEDUP_TOGGLE    = '//*[contains(@role,"button") and (contains(@aria-label,"Deduplicate") or contains(@aria-label,"dedup") or contains(@aria-label,"Timeline"))]'
    DATE_FILTER_BTN = '//*[contains(@role,"button") and (contains(@aria-label,"Date") or contains(@aria-label,"date range") or contains(@aria-label,"calendar"))]'
    EXPORT_CSV_BTN  = '//*[contains(@role,"button") and contains(@aria-label,"Export") and (contains(@aria-label,"CSV") or contains(@aria-label,"csv"))]'

    FIRST_CASE      = '(//flt-semantics[contains(@role,"button") and (contains(@aria-label,"Dr. ") or contains(., "Dr. ") or contains(@aria-label,"202") or contains(., "202"))])[1]'
    QUICK_VIEW_ITEM = '//*[contains(@aria-label,"View AI") or contains(@aria-label,"View Results")]'
    EDIT_PATIENT    = '//*[contains(@role,"button") and contains(@aria-label,"Edit")]'
    EXPORT_SINGLE   = '//*[contains(@role,"button") and (contains(@aria-label,"Export Single") or contains(@aria-label,"PDF Report"))]'

    SELECT_ALL      = '//*[contains(@role,"button") and contains(@aria-label,"Select All")]'
    BATCH_CSV       = '//*[contains(@role,"button") and (contains(@aria-label,"Batch Export CSV") or contains(@aria-label,"Batch CSV"))]'
    BATCH_PDF       = '//*[contains(@role,"button") and contains(@aria-label,"PDF Audit")]'

    RESET_FILTERS   = '//*[contains(@role,"button") and (contains(@aria-label,"Reset") or contains(@aria-label,"reset"))]'

    # Edit dialog
    EDIT_ID_FIELD   = '(//*[contains(@role,"textbox")])[1]'
    EDIT_NAME_FIELD = '(//*[contains(@role,"textbox")])[2]'
    SAVE_BTN        = '//*[contains(@role,"button") and contains(@aria-label,"Save")]'
    CANCEL_BTN      = '//*[contains(@role,"button") and contains(@aria-label,"Cancel")]'

    def search(self, query):
        return self.input_text(self.SEARCH_INPUT, query)

    def clear_search(self):
        return self.click_element(self.SEARCH_CLEAR)

    def filter_high(self):
        return self.click_element(self.FILTER_HIGH)

    def filter_intermediate(self):
        return self.click_element(self.FILTER_INTER)

    def filter_low(self):
        return self.click_element(self.FILTER_LOW)

    def toggle_biopsy_filter(self):
        return self.click_element(self.BIOPSY_FILTER)

    def toggle_grid_view(self):
        return self.click_element(self.GRID_TOGGLE)

    def toggle_dedup(self):
        return self.click_element(self.DEDUP_TOGGLE)

    def open_first_case_actions(self):
        return self.click_element(self.FIRST_CASE)

    def long_press_first_case(self):
        el = self.find_element(self.FIRST_CASE)
        if el:
            actions = ActionChains(self.driver)
            actions.click_and_hold(el).pause(1.5).release().perform()
            return True
        return False

    def export_csv(self):
        return self.click_element(self.EXPORT_CSV_BTN)

    def page_loaded(self):
        return super().page_loaded("Patient History", timeout=12)


# ─────────────────────────────────────────────────────────────────
#  CASE DETAIL PAGE
# ─────────────────────────────────────────────────────────────────
class CaseDetailPage(BasePage):
    BACK_BTN         = '//*[contains(@role,"button") and (contains(@aria-label,"back") or contains(@aria-label,"Back"))]'
    SHARE_BTN        = '//*[contains(@role,"button") and (contains(@aria-label,"Report") or contains(@aria-label,"Share") or contains(@aria-label,"share"))]'
    RISK_GAUGE       = '//*[contains(@aria-label,"Risk") or contains(@aria-label,"risk")]'
    PROGRESSION_CHART= '//*[contains(@aria-label,"progression") or contains(@aria-label,"trend") or contains(@aria-label,"chart")]'
    CLINICAL_DATA_A  = '//*[contains(@aria-label,"Smoking") or contains(@aria-label,"Demographics")]'

    def generate_pdf(self):
        self.inject_print_mock()
        return self.click_element(self.SHARE_BTN)

    def page_loaded(self, case_id=""):
        return super().page_loaded("Case Detail", timeout=12)


# ─────────────────────────────────────────────────────────────────
#  ANALYTICS PAGE
# ─────────────────────────────────────────────────────────────────
class AnalyticsPage(BasePage):
    SEARCH_INPUT    = '//*[contains(@role,"textbox") and (contains(@aria-label,"Search") or contains(@aria-label,"patient"))]'
    EXPORT_PDF_BTN  = '//*[contains(@role,"button") and (contains(@aria-label,"Export PDF") or contains(@aria-label,"Print") or contains(@aria-label,"print"))]'

    RANGE_7D        = '//*[contains(@aria-label,"7D") or contains(@aria-label,"7 day")]'
    RANGE_30D       = '//*[contains(@aria-label,"30D") or contains(@aria-label,"30 day")]'
    RANGE_6M        = '//*[contains(@aria-label,"6M") or contains(@aria-label,"6 month")]'
    RANGE_ALL       = '//*[contains(@aria-label,"ALL") or contains(@aria-label,"All Time")]'

    CHIP_INDURATED  = '//*[contains(@role,"button") and contains(@aria-label,"Indurated")]'
    CHIP_BLEEDING   = '//*[contains(@role,"button") and contains(@aria-label,"Bleeding")]'
    CHIP_TOBACCO    = '//*[contains(@role,"button") and contains(@aria-label,"Tobacco")]'
    CHIP_BIOPSY_REF = '//*[contains(@role,"button") and contains(@aria-label,"Biopsy Referral")]'

    STAT_HIGH_BOX   = '//*[contains(@aria-label,"High Risk") and contains(@role,"button")]'
    STAT_MED_BOX    = '//*[contains(@aria-label,"Medium") and contains(@role,"button")]'
    STAT_LOW_BOX    = '//*[contains(@aria-label,"Low Risk") and contains(@role,"button")]'

    HEATMAP_TONGUE  = '//*[contains(@role,"button") and contains(@aria-label,"Tongue")]'
    HEATMAP_BUCCAL  = '//*[contains(@role,"button") and contains(@aria-label,"Buccal")]'
    CLEAR_FILTERS   = '//*[contains(@role,"button") and (contains(@aria-label,"Clear Filters") or contains(@aria-label,"Reset All"))]'

    def search(self, query):
        return self.input_text(self.SEARCH_INPUT, query)

    def select_range_7d(self):
        return self.click_element(self.RANGE_7D)

    def select_range_all(self):
        return self.click_element(self.RANGE_ALL)

    def toggle_chip_indurated(self):
        return self.click_element(self.CHIP_INDURATED)

    def click_high_stat_box(self):
        return self.click_element(self.STAT_HIGH_BOX)

    def click_heatmap_tongue(self):
        return self.click_element(self.HEATMAP_TONGUE)

    def export_pdf(self):
        self.inject_print_mock()
        return self.click_element(self.EXPORT_PDF_BTN)

    def clear_filters(self):
        return self.click_element(self.CLEAR_FILTERS)

    def page_loaded(self):
        return super().page_loaded("Caseload Insights", timeout=12)


# ─────────────────────────────────────────────────────────────────
#  PROFILE PAGE
# ─────────────────────────────────────────────────────────────────
class ProfilePage(BasePage):
    AVATAR          = '//flt-semantics[contains(@role,"button") and (contains(@aria-label,"Profile Photo") or contains(., "Profile Photo"))]'
    VERIFIED_BADGE  = '//*[contains(@role,"button") and (contains(@aria-label,"Verified") or contains(@aria-label,"verified") or contains(@aria-label,"License"))]'

    BADGE_ROOKIE    = '//*[contains(@role,"button") and contains(@aria-label,"Rookie")]'
    BADGE_VETERAN   = '//*[contains(@role,"button") and contains(@aria-label,"Veteran")]'
    BADGE_SENTINEL  = '//*[contains(@role,"button") and contains(@aria-label,"Sentinel")]'
    ACHIEVEMENT_OK  = '//*[contains(@role,"button") and (contains(@aria-label,"OK") or contains(@aria-label,"ok"))]'

    SIGNATURE_BTN   = '//*[contains(@role,"button") and (contains(@aria-label,"Signature") or contains(@aria-label,"signature") or contains(@aria-label,"Capture Digital"))]'
    SIG_CLEAR       = '//*[contains(@role,"button") and contains(@aria-label,"Clear")]'
    SIG_SAVE        = '//*[contains(@role,"button") and contains(@aria-label,"Save Signature")]'
    SIG_CANVAS      = '//*[contains(@aria-label,"canvas") or contains(@aria-label,"sign here")]'
    RESET_SIG       = '//*[contains(@role,"button") and contains(@aria-label,"Reset")]'

    ID_BADGE_BTN    = '//*[contains(@role,"button") and (contains(@aria-label,"Badge") or contains(@aria-label,"Print") or contains(@aria-label,"ID Badge"))]'

    LICENSE_INPUT   = '//*[contains(@role,"textbox") and (contains(@aria-label,"License") or contains(@aria-label,"DCI") or contains(@aria-label,"Registration"))]'
    LICENSE_UPDATE  = '//*[contains(@role,"button") and contains(@aria-label,"Update")]'
    LICENSE_CANCEL  = '//*[contains(@role,"button") and contains(@aria-label,"Cancel")]'

    # Change password (in-page form)
    CHANGE_PW_TOGGLE= '//*[contains(@role,"button") and (contains(@aria-label,"Change") and contains(@aria-label,"Password") or contains(@aria-label,"Change Password"))]'
    CURRENT_PW      = '(//*[contains(@role,"textbox") and contains(@aria-label,"Current")])[1]'
    NEW_PW          = '(//*[contains(@role,"textbox") and contains(@aria-label,"New")])[1]'
    CONFIRM_PW      = '(//*[contains(@role,"textbox") and contains(@aria-label,"Confirm")])[1]'
    UPDATE_PW_BTN   = '//*[contains(@role,"button") and contains(@aria-label,"Update Password")]'

    SIGNOUT_BTN     = '//*[contains(@role,"button") and contains(@aria-label,"Sign Out")]'

    # Bottom sheet photo options
    CAMERA_OPTION   = '//*[contains(@role,"button") and (contains(@aria-label,"Camera") or contains(@aria-label,"camera"))]'
    CLOSE_SHEET     = '//*[contains(@role,"button") and contains(@aria-label,"Close")]'

    def open_avatar_sheet(self):
        return self.click_element(self.AVATAR)

    def click_badge_btn(self):
        self.inject_print_mock()
        return self.click_element(self.ID_BADGE_BTN)

    def open_achievement_rookie(self):
        return self.click_element(self.BADGE_ROOKIE)

    def open_license_dialog(self):
        return self.click_element(self.VERIFIED_BADGE)

    def open_signature_dialog(self):
        return self.click_element(self.SIGNATURE_BTN)

    def save_signature(self):
        # Draw on canvas then save
        canvas = self.find_element(self.SIG_CANVAS)
        if canvas:
            actions = ActionChains(self.driver)
            actions.move_to_element(canvas).move_by_offset(-40, -20).click_and_hold()
            actions.move_by_offset(80, 0).move_by_offset(0, 40).move_by_offset(-80, 0).release()
            actions.perform()
        return self.click_element(self.SIG_SAVE)

    def sign_out(self):
        try:
            self.driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
            time.sleep(1.0)
        except Exception:
            pass
        return self.click_element(self.SIGNOUT_BTN)

    def page_loaded(self):
        return self.element_exists(self.AVATAR, timeout=10)


# ─────────────────────────────────────────────────────────────────
#  SETTINGS PAGE
# ─────────────────────────────────────────────────────────────────
class SettingsPage(BasePage):
    # Preferences toggles — Semantics wrapper has aria-label → find child switch
    SW_HIGH_RISK_ALERT  = '//flt-semantics[contains(@aria-label,"High-risk alert banner")]//flt-semantics[contains(@role,"switch") or contains(@role,"checkbox")]'
    SW_AUTO_REFRESH     = '//flt-semantics[contains(@aria-label,"Auto-refresh dashboard")]//flt-semantics[contains(@role,"switch") or contains(@role,"checkbox")]'
    SW_COMPACT_VIEW     = '//flt-semantics[contains(@aria-label,"Compact case list")]//flt-semantics[contains(@role,"switch") or contains(@role,"checkbox")]'
    AI_MODE_DROPDOWN    = '//flt-semantics[contains(@role,"button") and (contains(@aria-label,"AI Diagnostic Mode") or contains(@aria-label,"Standard") or contains(@aria-label,"Screening"))]'

    # Department
    DEPT_DROPDOWN       = '//flt-semantics[contains(@role,"button") and (contains(@aria-label,"Department") or contains(@aria-label,"Oral Medicine"))]'
    FACILITY_INPUT      = '//flt-semantics[contains(@role,"textbox") and (contains(@aria-label,"Facility") or contains(@aria-label,"Clinic ID"))]'

    # Report toggles
    SW_SIGNATURE        = '//flt-semantics[contains(@aria-label,"Include signature line")]//flt-semantics[contains(@role,"switch") or contains(@role,"checkbox")]'
    SW_PATIENT_PHOTOS   = '//flt-semantics[contains(@aria-label,"Include patient photos")]//flt-semantics[contains(@role,"switch") or contains(@role,"checkbox")]'
    SW_DETAILED_AI      = '//flt-semantics[contains(@aria-label,"Detailed AI explanations")]//flt-semantics[contains(@role,"switch") or contains(@role,"checkbox")]'

    # Privacy
    SW_CONSENT          = '//flt-semantics[contains(@aria-label,"Require digital consent")]//flt-semantics[contains(@role,"switch") or contains(@role,"checkbox")]'
    SW_ACADEMIC         = '//flt-semantics[contains(@aria-label,"Academic sharing mode")]//flt-semantics[contains(@role,"switch") or contains(@role,"checkbox")]'

    # Security
    SW_BIOMETRIC        = '//flt-semantics[contains(@aria-label,"Biometric authentication")]//flt-semantics[contains(@role,"switch") or contains(@role,"checkbox")]'
    AUTO_LOCK_DD        = '//flt-semantics[contains(@role,"button") and (contains(@aria-label,"Auto-Lock") or contains(@aria-label,"Never") or contains(@aria-label,"5 minutes"))]'

    # Offline & Storage
    SW_OFFLINE          = '//flt-semantics[contains(@aria-label,"Offline mode")]//flt-semantics[contains(@role,"switch") or contains(@role,"checkbox")]'
    SW_WIFI_ONLY        = '//flt-semantics[contains(@aria-label,"Sync over Wi-Fi only")]//flt-semantics[contains(@role,"switch") or contains(@role,"checkbox")]'

    CLEAR_CACHE_TILE    = '//flt-semantics[contains(@aria-label,"Clear Offline Cache")]'
    EXPORT_CSV_TILE     = '//flt-semantics[contains(@aria-label,"Export Database to CSV")]'
    AUDIT_TILE          = '//flt-semantics[contains(@aria-label,"Monthly Audit Summaries")]'

    # Server
    SERVER_IP_TILE      = '//flt-semantics[contains(@aria-label,"Server IP Address")]'
    PING_TILE           = '//flt-semantics[contains(@aria-label,"Live Connection Ping")]'

    # Server dialog
    SERVER_DIALOG_INPUT = '//*[contains(@role,"textbox") and contains(@aria-label,"http")]'
    RESET_DEFAULT_BTN   = '//*[contains(@role,"button") and contains(@aria-label,"Reset to Default")]'
    SAVE_TEST_BTN       = '//*[contains(@role,"button") and (contains(@aria-label,"Save & Test") or contains(@aria-label,"Save and Test"))]'

    # About
    HOW_AI_TILE         = '//flt-semantics[contains(@aria-label,"How AI Works")]'
    PROTOCOL_TILE       = '//flt-semantics[contains(@aria-label,"Saveetha Diagnostic Protocol")]'
    DISCLAIMER_TILE     = '//flt-semantics[contains(@aria-label,"Medical Disclaimer")]'
    DIALOG_CLOSE        = '//*[contains(@role,"button") and (contains(@aria-label,"I Understand") or contains(@aria-label,"Close"))]'

    # Export tile dialog buttons
    EXPORT_OK_BTN       = '//*[contains(@role,"button") and contains(@aria-label,"OK")]'
    EXPORT_PRINT_BTN    = '//*[contains(@role,"button") and (contains(@aria-label,"Print") or contains(@aria-label,"PDF"))]'

    SIGNOUT_TILE        = '//flt-semantics[contains(@aria-label,"Sign Out")]'
    PROFILE_TILE        = '//flt-semantics[contains(@aria-label,"My Profile")]'
    CHANGE_PW_TILE      = '//flt-semantics[contains(@aria-label,"Change Password")]'

    def click_export_csv(self):
        return self.click_element(self.EXPORT_CSV_TILE)

    def click_clear_cache(self):
        return self.click_element(self.CLEAR_CACHE_TILE)

    def click_audit_pdf(self):
        self.inject_print_mock()
        return self.click_element(self.AUDIT_TILE)

    def open_server_dialog(self):
        return self.click_element(self.SERVER_IP_TILE)

    def reset_server_default(self):
        return self.click_element(self.RESET_DEFAULT_BTN)

    def save_and_test_server(self):
        return self.click_element(self.SAVE_TEST_BTN)

    def ping_server(self):
        return self.click_element(self.PING_TILE)

    def open_how_ai_dialog(self):
        return self.click_element(self.HOW_AI_TILE)

    def open_protocol_dialog(self):
        return self.click_element(self.PROTOCOL_TILE)

    def open_disclaimer_dialog(self):
        return self.click_element(self.DISCLAIMER_TILE)

    def close_dialog(self):
        return self.click_element(self.DIALOG_CLOSE)

    def sign_out(self):
        try:
            # Scroll to absolute bottom to expose the Sign Out button
            self.driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
            time.sleep(1.5)
            self.driver.find_element(By.TAG_NAME, 'body').send_keys(Keys.END)
            time.sleep(0.5)
        except Exception:
            pass
        return self.click_element(self.SIGNOUT_TILE)

    def page_loaded(self):
        return self.element_exists(self.SW_HIGH_RISK_ALERT, timeout=10)
